name: 'Install dependencies'
description: 'Install dependencies for building and publishing containers'

inputs:
  tag:
    description: Built container tag.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
  - name: Install python packages with older ansible for Centos 8
    if: ${{ inputs.tag == 'centos-8' }}
    shell: bash
    run: |
      sudo pip3 install ansible==9.8 passlib

  - name: Install python packages
    if: ${{ inputs.tag != 'centos-8' }}
    shell: bash
    run: |
      sudo pip3 install ansible passlib

  - name: Install deb packages
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y podman docker-compose

  - name: Print package versions
    shell: bash
    run: |
      podman --version
      crun --version
      ansible --version
      ansible-config dump --only-changed -t all

  - name: Enable podman socket
    shell: bash
    run: |
      sudo systemctl enable podman.socket
      sudo systemctl restart podman.socket
