name: 'Install dependencies'
description: 'Install dependencies for building and publishing containers'
runs:
  using: "composite"
  steps:
  - name: Install packages
    shell: bash
    run: |
      sudo pip3 install ansible
      sudo apt-get update
      sudo apt-get install -y podman docker-compose

  - name: Enable podman socket
    shell: bash
    run: |
      sudo systemctl enable --now podman.socket
