name: 'Install dependencies'
description: 'Install dependencies for building and publishing containers'

inputs:
  tag:
    description: Built container tag.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
  - name: Install python packages with older ansible for Centos 8
    if: ${{ inputs.tag == 'centos-8' }}
    shell: bash
    run: |
      sudo pip3 install ansible==9.8 passlib

  - name: Install python packages
    if: ${{ inputs.tag != 'centos-8' }}
    shell: bash
    run: |
      sudo pip3 install ansible passlib

  - name: Install deb packages
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y podman docker-compose

  - name: Print package versions
    shell: bash
    run: |
      podman --version
      crun --version
      ansible --version
      ansible-config dump --only-changed -t all

  - name: Workaround https://github.com/actions/runner-images/issues/7753
    shell: bash
    run: |
      curl -O http://archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containernetworking-plugins/containernetworking-plugins_1.1.1+ds1-3ubuntu0.24.04.2_amd64.deb
      sudo dpkg -i containernetworking-plugins_1.1.1+ds1-3ubuntu0.24.04.2_amd64.deb
      rm --force containernetworking-plugins_1.1.1+ds1-3ubuntu0.24.04.2_amd64.deb

  - name: Workaround https://github.com/containers/crun/issues/1308
    shell: bash
    run: |
      CRUN_VER='1.11.2'
      sudo curl -L "https://github.com/containers/crun/releases/download/${CRUN_VER}/crun-${CRUN_VER}-linux-amd64" -o "/usr/bin/crun"
      sudo chmod +x "/usr/bin/crun"
      crun --version

  - name: Enable podman socket
    shell: bash
    run: |
      sudo systemctl enable podman.socket
      sudo systemctl restart podman.socket
