name: 'Install dependencies'
description: 'Install dependencies for building and publishing containers'
runs:
  using: "composite"
  steps:
  - name: Install packages
    shell: bash
    run: |
      sudo pip3 install ansible
      sudo apt-get update
      sudo apt-get install -y podman docker-compose

  - name: Print package versions
    shell: bash
    run: |
      podman --version
      crun --version

  - name: Workaround https://github.com/actions/runner-images/issues/7753
    shell: bash
    run: |
      curl -O http://archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containernetworking-plugins/containernetworking-plugins_1.1.1+ds1-3_amd64.deb
      sudo dpkg -i containernetworking-plugins_1.1.1+ds1-3_amd64.deb
      rm --force containernetworking-plugins_1.1.1+ds1-3_amd64.deb

  - name: Workaround https://github.com/containers/crun/issues/1308
    shell: bash
    run: |
      CRUN_VER='1.11.2'
      sudo curl -L "https://github.com/containers/crun/releases/download/${CRUN_VER}/crun-${CRUN_VER}-linux-amd64" -o "/usr/bin/crun"
      sudo chmod +x "/usr/bin/crun"
      crun --version

  - name: Enable podman socket
    shell: bash
    run: |
      sudo systemctl enable podman.socket
      sudo systemctl restart podman.socket
