name: 'Install dependencies'
description: 'Install dependencies for building and publishing containers'
runs:
  using: "composite"
  steps:
  - name: Install packages
    shell: bash
    run: |
      sudo pip3 install ansible
      sudo apt-get update
      sudo apt-get install -y podman docker-compose

  - name: Print package versions
    shell: bash
    run: |
      podman --version
      crun --version

  - name: Enable podman socket
    shell: bash
    run: |
      sudo systemctl enable podman.socket
      sudo systemctl restart podman.socket
