name: 'Install dependencies'
description: 'Install dependencies for building and publishing containers'
runs:
  using: "composite"
  steps:
  - name: Install packages
    shell: bash
    run: |
      sudo pip3 install ansible
      sudo apt-get update
      sudo apt-get install -y podman docker-compose

      # Workaround https://github.com/actions/runner-images/issues/7753
      curl -O http://archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containernetworking-plugins/containernetworking-plugins_1.1.1+ds1-1_amd64.deb
      sudo dpkg -i containernetworking-plugins_1.1.1+ds1-1_amd64.deb
      rm --force containernetworking-plugins_1.1.1+ds1-1_amd64.deb

  - name: Enable podman socket
    shell: bash
    run: |
      sudo systemctl enable --now podman.socket
