- name: Configure SSH daemon
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/sshd.conf
    owner: root
    group: root
    mode: 0600
    content: |
      PermitRootLogin yes

- name: Start SSH daemon
  service:
    name: '{{ systemd.services.sshd }}'
    enabled: yes
    state: restarted
  register: restart_res
  until: "restart_res is not failed"
  # The ssh service restart sometimes gets stuck on VMs in openstack,
  # so we retry to make it more robust.
  retries: 5
  delay: 30
