- name: Configure SSH daemon
  template:
    src: sshd.conf
    dest: /etc/ssh/sshd_config.d
    owner: root
    group: root
    mode: 0600

- name: Start SSH daemon
  service:
    name: sshd.service
    enabled: yes
    state: started
