services:
  dns:
    restart: always
    image: ${REGISTRY}/ci-dns:latest
    container_name: dns
    env_file: ./env.containers
    volumes:
    - ./data/configs/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
    - NET_RAW
    - NET_ADMIN
    - SYS_CHROOT
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      sssd:
        ipv4_address: 172.16.100.2
  ipa:
    image: ${REGISTRY}/ci-ipa:${TAG}
    container_name: ipa
    hostname: master.ipa.test
    dns: 172.16.100.2
    env_file: ./env.containers
    volumes:
    - ./shared:/shared:rw
    cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
    - AUDIT_WRITE
    - SYS_CHROOT
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      sssd:
        ipv4_address: 172.16.100.10
  ldap:
    image: ${REGISTRY}/ci-ldap:${TAG}
    container_name: ldap
    hostname: master.ldap.test
    dns: 172.16.100.2
    env_file: ./env.containers
    volumes:
    - ./shared:/shared:rw
    cap_add:
    - SYS_PTRACE
    - AUDIT_WRITE
    - SYS_CHROOT
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      sssd:
        ipv4_address: 172.16.100.20
  samba:
    image: ${REGISTRY}/ci-samba:${TAG}
    container_name: samba
    hostname: dc.samba.test
    dns: 172.16.100.2
    env_file: ./env.containers
    volumes:
    - ./shared:/shared:rw
    cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
    - AUDIT_WRITE
    - SYS_CHROOT
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      sssd:
        ipv4_address: 172.16.100.30
  client:
    image: ${REGISTRY}/ci-client:${TAG}
    container_name: client
    hostname: client.test
    dns: 172.16.100.2
    env_file: ./env.containers
    volumes:
    - ./shared:/shared:rw
    cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
    - NET_RAW
    - NET_ADMIN
    - AUDIT_WRITE
    - SYS_CHROOT
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      sssd:
        ipv4_address: 172.16.100.40
  nfs:
    image: ${REGISTRY}/ci-nfs:${TAG}
    container_name: nfs
    hostname: nfs.test
    dns: 172.16.100.2
    env_file: ./env.containers
    volumes:
    - ./shared:/shared:rw
    - ./exports:/exports:rw
    cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
    - AUDIT_WRITE
    - SYS_CHROOT
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      sssd:
        ipv4_address: 172.16.100.50
  kdc:
    image: ${REGISTRY}/ci-kdc:${TAG}
    container_name: kdc
    hostname: kdc.test
    dns: 172.16.100.2
    env_file: ./env.containers
    volumes:
    - ./shared:/shared:rw
    - ./exports:/exports:rw
    cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
    - AUDIT_WRITE
    - SYS_CHROOT
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      sssd:
        ipv4_address: 172.16.100.60
networks:
  sssd:
    name: sssd-ci
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.100.0/24
         gateway: 172.16.100.1
