services:
  keycloak:
    image: ${REGISTRY}/ci-keycloak:${TAG}
    container_name: keycloak
    hostname: master.keycloak.test
    dns: 172.16.100.2
    env_file: ./env.containers
    cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
    - AUDIT_WRITE
    - AUDIT_CONTROL
    - NET_ADMIN
    - SYS_CHROOT
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      sssd:
        ipv4_address: 172.16.100.70
