---
# Users to be configured that their password never expires
ad_permanent_users:
- Administrator
- vagrant
# Skip vagrant-specific configuration of dns
skip_dns: no
# Skip installation of AD server
skip_addc_install: no
# Skip addition of sudo schema and possibly other ones
skip_schema: no
# Open firewall for all incomming traffic.
open_firewall: yes

# Temporary Directory for ADCS files for setup
temp_dir: 'C:\temp'
# Certificate Template Info
templates:
- { name: "EnrollmentAgent2", file: "enrollmentagent2.ldf" }
- { name: "SmartcardLogon4", file: "smartcardlogon4.ldf" }
