- name: Set distribution specific facts
  set_fact:
    systemd:
      services:
        kadmin: kadmin.service
        krb5kdc: krb5kdc.service
        sshd: sshd.service
    buildroot: yes
    debuginfo: yes
    passkey_support: Yes
    ipa_package: freeipa
    ca_trust_dir: /etc/pki/ca-trust/source/anchors/
    ca_trust_update: update-ca-trust
