- name: 'Include distribution specific tasks [{{ ansible_distribution }} {{ ansible_distribution_major_version }}]'
  include_tasks: '{{ include_file }}'
  loop_control:
    loop_var: include_file
  with_first_found:
  - files: '{{ ansible_distribution | distro_includes(ansible_distribution_major_version) }}'
