- name: 'Include distribution specific tasks [{{ ansible_facts["distribution"] }} {{ ansible_facts["distribution_major_version"] }}]'
  include_tasks: '{{ include_file }}'
  loop_control:
    loop_var: include_file
  with_first_found:
  - files: '{{ ansible_facts["distribution"] | distro_includes(ansible_facts["distribution_major_version"]) }}'
