- name: 'Facts are the same as in CentOS {{ ansible_distribution_major_version }}'
  include_tasks: '{{ include_centos }}'
  loop_control:
    loop_var: include_centos
  with_first_found:
  - files: '{{ "CentOS" | distro_includes(ansible_distribution_major_version) }}'

- name: Set distribution specific facts
  set_fact:
    buildroot: no
    debuginfo: no
    ipa: '{{ ipa_packages }}'

- name: Set distribution specific facts for RHEL 7
  set_fact:
    passkey_support: No
  when: ansible_distribution_major_version == '7'
