# Workaround for image mode where firewalld goes haywire after installation
- name: Reload dbus service
  ansible.builtin.systemd_service:
    name: dbus
    state: reloaded

- name: Start firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    enabled: yes
    state: restarted

- name: Set default firewalld zone to trusted
  command: firewall-cmd --set-default-zone=trusted
