- name: Create /root/localhost.inf
  template:
    src: instance.inf
    dest: /root/localhost.inf
    owner: root
    group: root
    mode: 0600

- name: Create directory server instance
  shell: |
    dscreate from-file /root/localhost.inf
  args:
    creates: '/etc/dirsrv/slapd-localhost'

- name: Install ldap certificate
  shell: |
    dsconf localhost security ca-certificate add --file /var/data/certs/ca.crt --name "sssd-ca"
    dsconf localhost security ca-certificate set-trust-flags "sssd-ca" --flags "CT,,"
    dsctl localhost tls import-server-key-cert /var/data/certs/master.ldap.test.crt /var/data/certs/master.ldap.test.key

- name: Grant read-only anonymous access
  shell: |
    ldapmodify -D "{{ service.ldap.bind.dn }}" -w "{{ service.ldap.bind.password }}" -H ldap://localhost -x
  args:
    stdin: |
      dn: {{ service.ldap.suffix }}
      changetype: modify
      add: aci
      aci: (targetattr=*)(version 3.0; acl "Enable anyone read"; allow (read, search, compare)(userdn="ldap:///anyone");)
  register: ldapmod
  failed_when:
  - 'ldapmod.rc != 0 and "ldap_modify: Type or value exists" not in ldapmod.stderr'

- name: 'Install additional schema: passkey'
  shell: |
    ldapmodify -D "{{ service.ldap.bind.dn }}" -w "{{ service.ldap.bind.password }}" -H ldap://localhost -x
  args:
    stdin: |
      dn: cn=schema
      changetype: modify
      add: attributeTypes
      attributeTypes: ( 2.16.840.1.113730.3.8.24.27 NAME 'passkey' DESC 'Passkey mapping' EQUALITY caseExactMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
      -
      add: objectclasses
      objectclasses: ( 2.16.840.1.113730.3.8.24.9 NAME 'passkeyUser' DESC 'IPA passkey user' AUXILIARY MAY passkey)

- name: Restart LDAP service
  service:
    name: dirsrv@localhost.service
    enabled: yes
    state: restarted
