name: 'Publish images'
inputs:
  credentials:
    description: Registry credentials.
    required: true
  tag:
    description: Output tag.
    required: true
  registry:
    description: Target image resigty.
    required: false
    default: "quay.io/sssd"
  extra_tags:
    description: Space separated list of extra tags.
    required: false
    default: ""
runs:
  using: "composite"
  steps:
  - name: Build containers
    shell: bash
    env:
      CREDENTIALS: ${{ inputs.credentials }}
    run: |
        authfile=`mktemp`
        trap "rm -f '$authfile' || :" EXIT
        sudo echo -e "$CREDENTIALS" > "$authfile"
        sudo make push                            \
          REGISTRY="${{ inputs.registry }}"       \
          TAG="${{ inputs.tag }}"                 \
          EXTRA_TAGS="${{ inputs.extra_tags }}"   \
          REGISTRY_AUTH_FILE="$authfile"
