test_venv: /opt/test_venv
#kver: "{{ ansible_facts['kernel'] | regex_replace('\\.[^.]*$', '') }}"
kver: "{{ ansible_facts['kernel'] | regex_replace('\\.' + ansible_facts['architecture'] + '$', '') }}"
