- name: 'Create /etc/krb5.conf.d directory'
  file:
    path: '/etc/krb5.conf.d'
    state: directory
    mode: 0755

- name: Create krb5.conf
  template:
    src: krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: Create Kerberos database
  shell: |
    /usr/sbin/kdb5_util -P "{{ service.kdc.master_password }}" create -s
  args:
    creates: "/var/kerberos/krb5kdc/principal"

- name: Start Kerberos services
  service:
    name: '{{ item }}'
    enabled: yes
    state: started
  with_items:
  - '{{ systemd.services.kadmin }}'
  - '{{ systemd.services.krb5kdc }}'
