- name: Remove default smb.conf
  file:
    path: /etc/samba/smb.conf
    state: absent

- name: Disable systemd-resolved to clear DNS port
  service:
    name: systemd-resolved.service
    enabled: no
    state: stopped

- name: Install Samba domain
  shell: |
    /usr/bin/samba-tool domain provision                        \
      --realm={{ service.samba.domain | upper | quote }}        \
      --domain={{ service.samba.netbios | quote }}              \
      --adminpass={{ service.samba.password | quote }}          \
      --krbtgtpass={{ service.samba.password | quote }}         \
      --dnspass={{ service.samba.password | quote }}            \
      --use-rfc2307
  args:
    creates: /etc/samba/smb.conf

- name: Setup Kerberos
  copy:
    src:  /var/lib/samba/private/krb5.conf
    dest: /etc/krb5.conf
    mode: 0644
    force: yes
    remote_src: yes

- name: Replace TLS certificates
  ini_file:
    path: /etc/samba/smb.conf
    section: global
    option: '{{ item.name }}'
    value: '{{ item.value }}'
    mode: 0600
  with_items:
  - { name: 'tls keyfile', value: '/data/certs/dc.samba.test.key' }
  - { name: 'tls certfile', value: '/data/certs/dc.samba.test.crt' }
  - { name: 'tls cafile', value: '/data/certs/ca.crt' }

- name: Select authselect winbind profile
  shell: |
    if [ ! -f /usr/bin/authselect ]; then
      exit 0
    fi

    authselect select winbind --force

- name: Enable schema extensions
  ini_file:
    path: /etc/samba/smb.conf
    section: global
    option: "dsdb:schema update allowed"
    value: true
    mode: '0600'
    backup: no

- name: Copy sudo schema
  copy:
    src: '{{ item }}'
    dest: '/etc/samba/{{ item }}'
  with_items:
  - sudo.attrs.ldif
  - sudo.class.ldif

- name: Install sudo schema
  shell: |
    export LDB_MODULES_PATH=/usr/lib64/samba/ldb
    ldbadd -H /var/lib/samba/private/sam.ldb /etc/samba/sudo.attrs.ldif
    ldbadd -H /var/lib/samba/private/sam.ldb /etc/samba/sudo.class.ldif

- name: Start Samba DC
  service:
    name: samba.service
    enabled: yes
    state: started

- name: Set default GPO
  shell: |
    # Make sure default default GptTmpl.inf exist, otherwise GPO access check will fail
    # on SSSD: https://bugzilla.redhat.com/show_bug.cgi?id=1839805#c18
    gpo=/var/lib/samba/sysvol/samba.test/Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}
    mkdir -p "$gpo/MACHINE/Microsoft/Windows NT/SecEdit"
    chown -R "SAMBA\domain admins":"SAMBA\domain admins" "$gpo"
    echo "[System Access]" > "$gpo/MACHINE/Microsoft/Windows NT/SecEdit/GptTmpl.inf"

- name: Create samba-sysvolreset.service
  template:
    src: samba-sysvolreset.service
    dest: /etc/systemd/system/samba-sysvolreset.service
    owner: root
    group: root
    mode: 0644

# sysvol permission must be reset every time the container is started
- name: Start samba-sysvolreset.service
  service:
    name: samba-sysvolreset.service
    enabled: yes
    state: started
