- name: Set /usr/bin/python to python3
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

- name: Create /etc/sudoers
  template:
    src: sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0600

- name: Copy common data
  synchronize:
    src: '{{ playbook_dir }}/../../data/'
    dest: /data/

# synchronize rsync option --chown was ignored for some reason
- name: Set correct permissions on /data
  shell: |
    chown -R root:root /data
    chmod -R 0755 /data
    chmod 0600 $(find /data -type f)
    chmod 0644 /data/certs/*.crt

- name: 'Change root password'
  user:
    name: root
    update_password: always
    password: '{{ user.root.password | password_hash("sha512") }}'

- name: 'Create /root/.ssh directory'
  file:
    path: '/root/.ssh'
    state: directory
    mode: 0700

- name: Copy root user ssh keys
  copy:
    src: '{{ playbook_dir }}/../../data/ssh-keys/{{ item.src }}'
    dest: '/root/.ssh/{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: '0600'
  with_items:
  - { src: 'root.id_rsa', dest: 'id_rsa' }
  - { src: 'root.id_rsa', dest: 'authorized_keys' }
  - { src: 'root.id_rsa.pub', dest: 'id_rsa.pub' }

- name: 'Create wheel group'
  group:
    name: wheel
    system: yes
    state: present

- name: 'Create {{ user.regular.name }} user'
  user:
    name: '{{ user.regular.name }}'
    uid: 1000
    groups: wheel
    append: yes
    shell: /usr/bin/bash
    password: '{{ user.regular.password | password_hash("sha512") }}'

- name: 'Create /home/{{ user.regular.name }}/.ssh directory'
  file:
    path: '/home/{{ user.regular.name }}/.ssh'
    state: directory
    mode: 0700

- name: Copy ci user ssh keys
  copy:
    src: '{{ playbook_dir }}/../../data/ssh-keys/{{ item.src }}'
    dest: '/home/{{ user.regular.name }}/.ssh/{{ item.dest }}'
    owner: '{{ user.regular.name }}'
    group: '{{ user.regular.name }}'
    mode: '0600'
  with_items:
  - { src: 'ci.id_rsa', dest: 'id_rsa' }
  - { src: 'ci.id_rsa', dest: 'authorized_keys' }
  - { src: 'ci.id_rsa.pub', dest: 'id_rsa.pub' }
