- name: Install Active Directory Services
  win_feature:
    name: '{{ item }}'
    include_management_tools: yes
    include_sub_features: yes
    state: present
  with_items:
  - AD-Domain-Services
  - DNS

- name: 'Create new AD forest {{ ad_domain }}'
  win_shell: |
    Import-Module ADDSDeployment

    Install-ADDSForest                                                        \
      -DomainName "{{ ad_domain }}"                                           \
      -CreateDnsDelegation:$false                                             \
      -ForestMode "WinThreshold"                                              \
      -DomainMode "WinThreshold"                                              \
      -Force:$true                                                            \
      -InstallDns:$true                                                       \
      -NoRebootOnCompletion:$true                                             \
      -SafeModeAdministratorPassword                                          \
        (ConvertTo-SecureString '{{ ad_password }}' -AsPlainText -Force)
  register: installation
  args:
    creates: 'C:\Windows\NTDS'

- name: Reboot machine
  win_reboot:
  when: installation.changed

- name: Install AD Certificate Services
  win_feature:
    name: AD-Certificate
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: adcs_feature

- name: Configure Enterprise Root CA
  win_shell: |
    Import-Module ADCSDeployment
    Install-AdcsCertificationAuthority \
      -CAType EnterpriseRootCA \
      -CryptoProviderName "RSA#Microsoft Software Key Storage Provider" \
      -KeyLength 2048 \
      -HashAlgorithmName SHA256 \
      -Force
  args:
    creates: 'C:\Windows\System32\CertSrv'

- name: Install AD CS Web Enrollment
  win_feature:
    name: ADCS-Web-Enrollment
    include_management_tools: yes
    state: present
