- name: Copy sudo schema to guest
  win_copy:
    src: '{{ item }}.schema'
    dest: 'C:\{{ item }}.schema'
  with_items:
  - sudo

- name: Install additional schemas
  win_shell: |
    ldifde -i -f C:\{{ item }}.schema -c dc=X {{ ad_suffix }} -b "Administrator" "{{ ad_domain }}" "{{ ansible_password }}"
  register: schema
  failed_when: schema.rc != 0 and schema.stdout is not search('ENTRY_EXISTS')
  changed_when: schema.rc == 0
  with_items:
  - sudo
