- name: Install buildroot repository
  block:
  - name: Install dnf plugins
    dnf:
      state: present
      name:
      - dnf-plugins-core

  - name: 'Install additional repositories'
    template:
      src: repo
      dest: '/etc/yum.repos.d/{{ item.name }}.repo'
      owner: root
      group: root
      mode: 0644
    with_items:
    - {name: 'buildroot', url: 'https://kojihub.stream.centos.org/kojifiles/repos/c9s-build/latest/$basearch'}

  - name: Install EPEL and @sssd/ci-deps repositories
    shell: |
      set -ex
      rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
      dnf install --setopt=install_weak_deps=False -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      dnf copr enable -y @sssd/ci-deps
    args:
      warn: False

  # Required until https://pagure.io/copr/copr/issue/2106 gets fixed
  - name: Disable gpgcheck for @sssd/cli-deps
    ini_file:
      path: '/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_sssd:ci-deps.repo'
      section: 'copr:copr.fedorainfracloud.org:group_sssd:ci-deps'
      option: 'gpgcheck'
      value: 'false'
      mode: 0644
  when: inventory_hostname == 'base-ground'

- name: 'Packages are the same as in Fedora'
  include_tasks: 'Fedora.yml'