- name: Install buildroot repository
  block:
  - name: Install dnf plugins
    dnf:
      state: present
      name:
      - dnf-plugins-core

  - name: Ensure the powertools repository is enabled
    community.general.dnf_config_manager:
      name: powertools
      state: enabled
    when: buildroot

  - name: Install EPEL repository
    dnf:
      state: present
      name:
      - epel-release

  - name: Enable IdM module
    shell: |
      dnf module enable -y idm:DL1
  when: "'base_ground' in group_names"

- name: 'Packages are the same as in Fedora'
  include_tasks: 'Fedora.yml'