- name: Install buildroot repository
  block:
  - name: Install buildroot
    template:
      src: repo
      dest: '/etc/yum.repos.d/{{ item.name }}.repo'
      owner: root
      group: root
      mode: 0644
    with_items:
    - {name: 'buildroot', url: 'https://kojihub.stream.centos.org/kojifiles/repos/c9s-build/latest/$basearch'}
    when: buildroot

  - name: Install EPEL and @sssd/ci-deps repositories
    shell: |
      set -ex
      rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
      dnf install --setopt=install_weak_deps=False -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  when: "'base_ground' in group_names"

- name: 'Packages are the same as in Fedora'
  include_tasks: 'Fedora.yml'