- name: Install buildroot repository
  block:
  - name: Install dnf plugins
    dnf:
      state: present
      name:
      - dnf-plugins-core

  - name: Ensure the crb repository is enabled
    community.general.dnf_config_manager:
      name: crb
      state: enabled
    when: buildroot

  - name: Install EPEL and @sssd/ci-deps repositories
    shell: |
      set -ex
      rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
      dnf install --setopt=install_weak_deps=False -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  when: "'base_ground' in group_names"

- name: 'Packages are the same as in Fedora'
  include_tasks: 'Fedora.yml'