- name: Install packages for ground base image
  block:
  - name: Install systemd and common tools
    apt:
      state: present
      update_cache: yes
      name:
      - bash-completion
      - bind9utils
      - dbus
      - e2fsprogs
      - expect
      - findutils
      - firewalld
      - gdb
      - gdbserver
      - git
      - iputils-*
      - ldap-utils
      - ldb-tools
      - less
      - man
      - mc
      - net-tools
      - openssh-client
      - openssh-server
      - passwd
      - python3-pip
      - rsync
      - sudo
      - systemd
      - tcpdump
      - tig
      - tmux
      - tshark
      - vim
      - wget
  when: "'base_ground' in group_names"

- name: Enable backports repo to install freeipa
  block:
  - name: Enable backports repo
    copy:
      dest: /etc/apt/sources.list.d/backports.list
      content: "deb http://deb.debian.org/debian bullseye-backports main"
      owner: root
      group: root
      mode: '0644'

- name: Install packages for client base image
  block:
  - name: Install SSSD and its dependencies
    apt:
      state: present
      update_cache: yes
      name:
      - adcli
      - freeipa-client
      - nfs-common
      - packagekit
      - realmd
      - sssd
      - sssd-*
  when: "'base_client' in group_names"

- name: Install packages for NFS base image
  block:
  - name: Install NFS
    apt:
      state: present
      update_cache: yes
      name:
      - nfs-kernel-server
  when: "'base_nfs' in group_names"

- name: Install packages for KDC base image
  block:
  - name: Install KDC
    apt:
      state: present
      update_cache: yes
      name:
      - krb5-admin-server
      - krb5-config
      - krb5-kdc
  when: "'base_kdc' in group_names"

- name: Install packages for Keycloak base image
  block:
  - name: Install Keycloak dependencies
    apt:
      state: present
      update_cache: yes
      name:
      - openjdk-11-jre-headless
      - openssl
      - unzip
      - ca-certificates
  when: "'base_keycloak' in group_names"

- name: Install additional packages for client development image
  block:
  - name: Install SSSD build and integration tests dependencies
    apt:
      state: present
      update_cache: yes
      name:
      - adcli
      - autoconf
      - automake
      - autopoint
      - check
      - cifs-utils
      - clang
      - dh-apparmor
      - dnsutils
      - docbook-xml
      - docbook-xsl
      - fakeroot
      - faketime
      - gettext
      - gnutls-bin
      - krb5-admin-server
      - krb5-config
      - krb5-kdc
      - krb5-user
      - lcov
      - libc-ares-dev
      - libcmocka-dev
      - libcollection-dev
      - libcurl4-openssl-dev
      - libdbus-1-dev
      - libdhash-dev
      - libglib2.0-dev
      - libhttp-parser-dev
      - libini-config-dev
      - libjansson-dev
      - libkeyutils-dev
      - libkrad-dev
      - libkrb5-dev
      - libldap2-dev
      - libldb-dev
      - libltdl-dev
      - libnfsidmap-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libnspr4-dev
      - libnss-wrapper
      - libnss3-dev
      - libp11-kit-dev
      - libpam-wrapper
      - libpam0g-dev
      - libpcre2-dev
      - libpcre3-dev
      - libpopt-dev
      - libsasl2-dev
      - libselinux1-dev
      - libsemanage1-dev
      - libsmbclient-dev
      - libssl-dev
      - libssl-dev
      - libsystemd-dev
      - libtalloc-dev
      - libtdb-dev
      - libtevent-dev
      - libtool
      - libtool-bin
      - libuid-wrapper
      - libunistring-dev
      - libxml2-utils
      - lsb-release
      - make
      - packagekit
      - python3-dbus
      - python3-dev
      - python3-ldap
      - python3-ldb
      - python3-psutil
      - python3-pycodestyle
      - python3-pytest
      - python3-requests
      - samba-dev
      - slapd
      - softhsm2
      - uuid-dev
      - valgrind
      - xml-core
      - xsltproc

  - name: Install additional python packages
    pip:
      name:
      - flaky
  when: "'client_devel' in group_names"
