- name: Enable idm module
  command: yum module enable idm:DL1 -y
  when: ansible_distribution_major_version == '8'

- name: Install EPEL repository
  dnf:
    state: present
    name:
    - epel-release
  when: extended_packageset

- name: 'Packages are the same as in Fedora'
  include_tasks: 'Fedora.yml'
