- name: Enable idm module
  command: yum module enable idm:DL1 -y
  when: ansible_distribution_major_version == '8'

- name: Install EPEL repository
  dnf:
    state: present
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm'
    disable_gpg_check: yes
  when: extended_packageset

- name: 'Packages are the same as in Fedora'
  include_tasks: 'Fedora.yml'
