- name: 'Packages are the same as in CentOS {{ ansible_distribution_major_version }}'
  include_tasks: '{{ include_centos }}'
  loop_control:
    loop_var: include_centos
  with_first_found:
  - files: '{{ "CentOS" | distro_includes(ansible_distribution_major_version) }}'
