---
- name: Set AD facts
  set_fact:
    ad_domain: "{{ '.'.join(groups.ad.0.split('.')[1:]) }}"
    safe_password: "{{ service.ad.safe_password }}"
    ad_keytab: /var/enrollment/{{ '.'.join(groups.ad.0.split('.')[1:]) }}.keytab

- name: Stat {{ ad_keytab }} to detect that we are already joined to AD
  stat:
    path:  "{{ ad_keytab }}"
  register: enrollment_ad_1

- name: Create /etc/krb5.conf for AD join
  template:
    src: krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: Join AD domain
  command: realm join {{ ad_domain | quote }} --verbose
  args:
    stdin: '{{ safe_password }}'
  when: not enrollment_ad_1.stat.exists

- name: Stat {{ ad_keytab }}
  stat:
    path: "{{ ad_keytab }}"
  register: enrollment_ad

- name: Copy AD keytab to "{{ ad_keytab }}"
  copy:
    src: /etc/krb5.keytab
    dest: "{{ ad_keytab }}"
    mode: 0600
    remote_src: yes
  when: not enrollment_ad.stat.exists

- name: Cleanup after joining the AD domain
  file:
    path: '{{ item }}'
    state: absent
  with_items:
  - /etc/krb5.conf
  - /etc/krb5.keytab
  - /etc/sssd/sssd.conf
