---
- name: Set Samba facts
  set_fact:
    samba_domain: "{{ hostvars[groups.samba.0]['samba_domain'] }}"
    samba_password: "{{ hostvars[groups.samba.0].ansible_password | default(service.samba.password) }}"
    samba_keytab: /var/enrollment/{{ hostvars[groups.samba.0]['samba_domain'] }}.keytab

- name: Stat {{ samba_keytab }} to detect that we are already joined
  stat:
    path: "{{ samba_keytab }}"
  register: enrollment_samba_1

- name: Create /etc/krb5.conf for samba join
  template:
    src: krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: Realm join Samba domain
  command: realm join {{ samba_domain | quote }} --verbose
  args:
    stdin: '{{ samba_password }}'
  when: not enrollment_samba_1.stat.exists

- name: Stat {{ samba_keytab }}
  stat:
    path: "{{ samba_keytab }}"
  register: enrollment_samba

- name: Copy Samba keytab to {{ samba_keytab }}
  copy:
    src: /etc/krb5.keytab
    dest: "{{ samba_keytab }}"
    mode: 0600
    remote_src: yes
  when: not enrollment_samba.stat.exists

- name: Cleanup after joining the Samba domain
  file:
    path: '{{ item }}'
    state: absent
  with_items:
  - /etc/krb5.conf
  - /etc/krb5.keytab
  - /etc/sssd/sssd.conf

- name: Add samba to domains
  set_fact:
    domains: "{{ domains + [samba_domain] }}"
