- name: Set facts for client
  set_fact:
    domains: []
    client_fqdn: "{{ inventory_hostname }}"

- name: Check if we are running in image mode
  stat:
    path: /usr/bin/rpm-ostree
  register: rpm_ostree

- name: Create /var/enrollment directory
  file:
    path: /var/enrollment
    state: directory
    owner: root
    group: root
    mode: '0700'

# Backward compatibility symlink
- name: Create symlink /enrollment to /var/enrollment
  ansible.builtin.file:
    src: '/var/enrollment'
    dest: '/enrollment'
    state: link
    owner: root
    group: root
  when:
  - not rpm_ostree.stat.exists

- name: Join IPA domain
  ansible.builtin.include_tasks:
    file: enroll_IPA.yml
  when:
  - '"ipa" in groups and groups["ipa"]'
  - join_ipa

- name: Join Samba domain
  ansible.builtin.include_tasks:
    file: enroll_samba.yml
  when:
  - '"samba" in groups and groups["samba"]'
  - join_samba

- name: Join ldap domain
  block:
  - name: Add ldap to domains
    set_fact:
      domains: "{{ domains + [service.ldap.domain] }}"
  when:
  - '"ldap" in groups and groups["ldap"]'
  - join_ldap

- name: Join AD
  ansible.builtin.include_tasks:
    file: enroll_AD.yml
  when:
  - '"ad" in groups and groups["ad"]'
  - join_ad

- name: Stop SSSD
  service:
    name: sssd.service
    enabled: yes
    state: stopped

- name: Create /etc/sssd/sssd.conf
  template:
    src: sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600

- name: Create /etc/krb5.conf
  template:
    src: krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: Set SELinux label for /var/enrollment
  shell: |
    if selinuxenabled; then
      semanage fcontext -a -t etc_t "/var/enrollment(/.*)*"
      restorecon -R -v /var/enrollment
    else
      exit 0
    fi

- name: Show configured domains
  debug:
    msg: "domains = {{ ', '.join(domains) }}"
