- name: Install usbip for normal kernels on non-containers
  block:
  - name: Create temporary build directory
    tempfile:
      state: directory
      suffix: usbip_build
    register: build_dir

  - name: Ensure Koji config directory exists
    file:
      path: "~/.koji/config.d"
      state: directory
      mode: '0755'

  - name: Configure CentOS Stream Koji profile
    copy:
      dest: "~/.koji/config.d/centos-stream.conf"
      content: |
        [centos-stream]
        server = https://kojihub.stream.centos.org/kojihub
        topurl = https://kojihub.stream.centos.org/kojifiles

  - name: Download Kernel Source RPM via Koji
    command:
      cmd: "koji --profile centos-stream download-build --arch=src kernel-{{ kver }}"
      chdir: "{{ build_dir.path }}"
    args:
      creates: "{{ build_dir.path }}/kernel-{{ kver }}.src.rpm"

  - name: Extract Source RPM and Kernel Tarball
    shell: |
      set -ex
      rpm2cpio kernel-{{ kver }}.src.rpm | cpio -id
      xz -dc linux-{{ kver }}.tar.xz | tar xf -
    args:
      chdir: "{{ build_dir.path }}"
      creates: "{{ build_dir.path }}/linux-{{ kver }}/tools/usb/usbip/configure"

  - name: Build and Install USBIP tools
    shell: |
      set -ex
      ./autogen.sh
      ./configure
      make install
    args:
      chdir: "{{ build_dir.path }}/linux-{{ kver }}/tools/usb/usbip/"
      creates: "/usr/local/sbin/usbip"

  - name: Create symlink for usbip
    file:
      src: /usr/local/sbin/usbip
      dest: /usr/sbin/usbip
      state: link
  when: ansible_virtualization_type not in ["podman", "docker"]
