---
- hosts: services
  gather_facts: yes
  roles:
  - facts
  - firewall

- hosts: master.ldap.test
  gather_facts: no
  roles:
  - ldap

- hosts: dc.samba.test
  gather_facts: no
  roles:
  - samba

- hosts: master.ipa.test
  gather_facts: no
  roles:
  - ipa
  - { role: passkey, when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" }

- hosts: client.test
  gather_facts: no
  roles:
  - client
  - { role: passkey, when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" }

- hosts: nfs.test
  gather_facts: no
  roles:
  - nfs

- hosts: kdc.test
  gather_facts: no
  roles:
  - kdc

- hosts: master.keycloak.test
  gather_facts: no
  roles:
  - keycloak

- hosts: services
  gather_facts: no
  roles:
  - ssh_server
  - cleanup
