---
- hosts: all
  gather_facts: yes
  roles:
  - dns

- name: Include base
  ansible.builtin.import_playbook: playbook_image_base.yml
  vars:
    passkey_support: "{{ override_passkey_support | default('no') | bool }}"
    user_regular_uid: 1024
    ansible_become: yes
    extended_packageset: "{{ override_extended_packageset | default('no') | bool }}"
    virt_smarcard: "{{ override_virt_smarcard | default('no') | bool }}"

- name: Include services
  ansible.builtin.import_playbook: playbook_image_service.yml
  vars:
    passkey_support: "{{ override_passkey_support | default('no') | bool }}"
    user_regular_uid: 1024
    ansible_become: yes
    join_ad: "{{ override_join_ad | default('no') | bool }}"
    join_ldap: "{{ override_join_ldap | default('no') | bool }}"
    join_samba: "{{ override_join_samba | default('no') | bool }}"
    join_ipa: "{{ override_join_ipa | default('no') | bool }}"
    trust_ipa_samba: "{{ override_trust_ipa_samba | default('no') | bool }}"
    trust_ipa_ad: "{{ override_trust_ipa_ad | default('no') | bool }}"
    trust_ipa_ad_two_way: "{{ override_trust_ipa_ad_two_way | default('no') | bool }}"
    extended_packageset: "{{ override_extended_packageset | default('no') | bool }}"
    skip_cleanup: true
    virt_smarcard: "{{ override_virt_smarcard | default('no') | bool }}"

- hosts: ad
  gather_facts: yes
  roles:
  - { role: ad, skip_addc_install: yes, skip_dns: yes, ad_permanent_users: ['Administrator'] }
