---
- hosts: services
  gather_facts: yes
  roles:
  - facts
  - firewall
  - no_nscd

- hosts: ldap
  gather_facts: no
  roles:
  - ldap

- hosts: samba
  gather_facts: no
  roles:
  - samba

- hosts: ipa
  gather_facts: no
  roles:
  - ipa
  - { role: passkey, when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" }
  - { role: ipasmartcard, when: ansible_os_family == 'RedHat' and virt_smartcard }

- hosts: client
  gather_facts: no
  roles:
  - client
  - { role: passkey, when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" }
  - { role: virtsmartcard, when: ansible_distribution != "Ubuntu" and ansible_distribution != "Debian" and virt_smartcard }
  - { role: ipasmartcard, when: ansible_os_family == 'RedHat' and virt_smartcard }

- hosts: nfs
  gather_facts: no
  roles:
  - nfs

- hosts: kdc
  gather_facts: no
  roles:
  - kdc

- hosts: keycloak
  gather_facts: no
  roles:
  - keycloak

- hosts: services
  gather_facts: no
  roles:
  - ssh_server

- hosts: services
  gather_facts: no
  roles:
  - role: cleanup
    when: skip_cleanup is undefined or not skip_cleanup
