---
- hosts: services
  gather_facts: yes
  roles:
  - facts

- hosts: master.ldap.test
  gather_facts: no
  roles:
  - ldap

- hosts: dc.samba.test
  gather_facts: no
  roles:
  - samba

- hosts: master.ipa.test
  gather_facts: no
  roles:
  - ipa

- hosts: client.test
  gather_facts: no
  roles:
  - client

- hosts: nfs.test
  gather_facts: no
  roles:
  - nfs

- hosts: kdc.test
  gather_facts: no
  roles:
  - kdc

- hosts: services
  gather_facts: no
  roles:
  - ssh_server
  - cleanup
