name: Build
on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/build.yml'
    - 'src/**'
    - 'data/**'
    - 'docker-compose.yml'
  pull_request:
    paths:
    - '.github/workflows/build.yml'
    - 'src/**'
    - 'data/**'
    - 'docker-compose.yml'
  workflow_dispatch:
  schedule:
  - cron: '0 1 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  ANSIBLE_FORCE_COLOR: 1
  DOCKER_HOST: unix:///run/podman/podman.sock
jobs:
  other:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image: [
          { base: 'quay.io/centos/centos:stream8', tag: 'centos-8', extra: '', unavailable: 'samba' },
        ]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Build images
      uses: ./.github/actions/build
      with:
        base_image: ${{ matrix.image.base }}
        tag: ${{ matrix.image.tag }}
        unavailable: ${{ matrix.image.unavailable }}

    - name: Publish images
      if: github.event_name != 'pull_request'
      uses: ./.github/actions/publish
      with:
        credentials: ${{ secrets.QUAY_IO_CREDENTIALS }}
        tag: ${{ matrix.image.tag }}
        extra_tags: ${{ matrix.image.extra }}
